// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoControleDeEstoque.Models.Context;

#nullable disable

namespace ProjetoControleDeEstoque.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoControleDeEstoque.Models.Entites.Feedback", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedBackDescricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("ProjetoControleDeEstoque.Models.Entites.Fornecedor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CnpjCpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("ProjetoControleDeEstoque.Models.Entites.LinkDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FeedbackId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FornecedorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Href")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metodo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<string>("Rel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("LinkDTO");
                });

            modelBuilder.Entity("ProjetoControleDeEstoque.Models.Entites.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoProduto")
                        .HasColumnType("int");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("int");

                    b.Property<string>("FornecedorId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Localizacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId1");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("ProjetoControleDeEstoque.Models.Entites.LinkDTO", b =>
                {
                    b.HasOne("ProjetoControleDeEstoque.Models.Entites.Feedback", null)
                        .WithMany("Links")
                        .HasForeignKey("FeedbackId");

                    b.HasOne("ProjetoControleDeEstoque.Models.Entites.Fornecedor", null)
                        .WithMany("Links")
                        .HasForeignKey("FornecedorId");

                    b.HasOne("ProjetoControleDeEstoque.Models.Entites.Produto", null)
                        .WithMany("Links")
                        .HasForeignKey("ProdutoId");
                });

            modelBuilder.Entity("ProjetoControleDeEstoque.Models.Entites.Produto", b =>
                {
                    b.HasOne("ProjetoControleDeEstoque.Models.Entites.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId1");

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("ProjetoControleDeEstoque.Models.Entites.Feedback", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("ProjetoControleDeEstoque.Models.Entites.Fornecedor", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("ProjetoControleDeEstoque.Models.Entites.Produto", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
